---
- name: NPM Install
  shell: "npm install"
  args:
    chdir: "{{ domain_path }}"
  when: build_assets
  tags:
    - deploy_laravel

- name: NPM Run
  shell: "npm run production --silent"
  args:
    chdir: "{{ domain_path }}"
  when: build_assets
  tags:
    - deploy_laravel
