- name: Composer Install
  composer:
    command: install
    working_dir: "{{ domain_path }}"
    no_dev: "{{ require_composer_no_dev }}"
  environment:
    COMPOSER_NO_INTERACTION: "1"
    COMPOSER_ALLOW_SUPERUSER: "1"
  tags:
    - deploy_laravel
