- name: Add CRON task scheduling [artisan schedule:run]
  cron:
    job: "cd {{ domain_path}} && php artisan schedule:run >> /dev/null 2>&1"
    name: "task scheduling {{ domain }}"
    minute: "*"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
