- name: Check if site is already deployed
  stat:
    path: "{{ domain_path }}/artisan"
  register: site_already_deployed

- name: Down Application
  shell: php artisan down
  args:
    chdir: "{{ domain_path }}"
  when: site_already_deployed.stat.exists
