---
- import_tasks: down.yml
- import_tasks: git.yml
- import_tasks: composer.yml
- import_tasks: env.yml

- import_tasks: migration.yml
  when: execute_migration

- import_tasks: assets.yml
- import_tasks: owner.yml
- import_tasks: cache.yml
- import_tasks: key.yml
- import_tasks: cron.yml
  when: set_cron

- import_tasks: supervisor.yml
  when: set_supervisor

- import_tasks: up.yml
- import_tasks: queue.yml

