- name: Set group to www-data
  file:
    path: "{{ deploy_laravel_dest }}/{{ deploy_laravel_domain }}"
    state: directory
    owner: "{{ user }}"
    group: www-data
    recurse: yes
  become: true
  tags:
    - deploy_laravel
