- name: Install supervisor
  apt:
    name: "supervisor"
    state: present
    update_cache: yes
  become: true

- name: Create supervisor configuration file
  template:
    src: templates/supervisor.j2
    dest: "/etc/supervisor/conf.d/{{ domain.split('.')[0] | lower }}_queue_worker_default.conf"
  become: true
  tags:
    - deploy_laravel

- name: supervisorctl reread
  shell: supervisorctl reread
  become: true

- name: supervisorctl update
  shell: supervisorctl update
  become: true

- name: supervisorctl restart all
  shell: supervisorctl restart all
  become: true